version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10001:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
